name: Weekly On-Call Slack Post

on:
  workflow_dispatch:  # allow manual runs too
#   schedule:
#     - cron: '0 9 * * 1'  # every Monday at 9 AM UTC
  
jobs:
  post-oncall:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run On-Call Poster
        env:
          PD_API_KEY: ${{ secrets.PD_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SCHEDULE_ID: ${{ secrets.PD_SCHEDULE_ID }}
        run: |
          python scripts/post-oncall-schedule.py